#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default cmolorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    [[layers]]
    name = "colorscheme"
    [options]
    colorscheme = "palenight"
    #colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enable_vimfiler_gitstatus = true
    updatetime = 100
    
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       # 'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "lang#go"
  #go_interpreter = '~/download/bin/go'
[[layers]]
  name = "lang#python"
[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true
[[layers]]
  name = "git"
  git-plugin = "fugitive"
  enable_mru = true
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "VersionControl"

[[layers]]
  name = 'checkers'
[[layers]] 
  name = 'debug'
[[layers]]
  name = 'lsp'
[[layers]]
 name = 'snippet' 
 [[layers]]
 name = 'statusline'
[[layers]]
  name = 'debugger'
debugger_default = 'pdb'
[[layers]]
  name = 'tabnine'
	

#Everything after this line is bs
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
#BULLSHIT
[[custome_plugin]]
  name = "SirVer/ultisnips"

[[custome_plugin]]
  name = "stevearc/vim-arduino"

[[custome_plugin]]
  name = "Shougo/vimproc"

[[custome_plugin]]
 name = "luochen1990/rainbow"

[[custome_plugin]]
 name = "stevearc/vim-arduino"

[[custom_plugins]]
  name = "sebdah/vim-delve"

[[custom_plugins]]
  name = "AndrewRadev/splitjoin.vim"

[[custom_plugins]]
  name = "SirVer/ultisnips"

[[custom_plugins]]
  name = "puremourning/vimspector"

[[custom_plugins]]
  name = "cdelledonne/vim-cmake"

[[custom_plugins]]
  name = "drewtempelmeyer/palenight.vim"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "default"

[[layers]]
  name = "sudo"

[[layers]]
  name="edit"

[[layers]]
  name="tools"

[[layers]]
  name="core"

[[layers]]
  name="core#banner"

[[layers]]
  name="core#tabline"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
[layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

go_rename_command = 'gopls'
go_metalinter_command='golangci-lint'
go_metalinter_autosave = true
go_metalinter_enabeld = ['deadcode', 'errcheck', 'gosimple', 'govet', 'staticcheck', 'typecheck', 'unused', 'varcheck']

